create table worker (
    id      integer generated by default as identity primary key,
    name    varchar(100),
    surname varchar(100),
    email   varchar
);

create table client (
    id            integer generated by default as identity primary key,
    name          varchar(50),
    date          date,
    manager       varchar(20),
    comment       varchar(120),
    status        char,
    date_complete timestamp,
    id_worker     integer references worker(id) on delete set null
);

create table product (
    id        integer generated by default as identity primary key,
    name      varchar(80),
    amount    double precision,
    packing   smallint,
    comment   varchar(120),
    client_id integer references client(id) on delete cascade,
    status    char
);

INSERT INTO worker (name, surname, email) VALUES ('John', 'Doe', 'johndoe@example.com');